{application,shuwa_task,
             [{description,[25968,34521,20219,21153,31649,29702]},
              {vsn,"4.0.0"},
              {modules,[shuwa_instruct,shuwa_task_app,shuwa_task_channel,
                        shuwa_task_handler,shuwa_task_sup,task_loader,
                        task_sup,task_worker]},
              {registered,[shuwa_task_sup]},
              {applications,[kernel,stdlib,shuwa_framework]},
              {mod,{shuwa_task_app,[]}}]}.
